apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: tips-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 1234
      nodePort: 30080
  type: NodePort
