apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: tips-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tips-db
  template:
    metadata:
      labels:
        app: tips-db
    spec:
      containers:
        - name: tips-db-container
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: tips-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: tips-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: tips-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
