apiVersion: apps/v1
kind: Deployment
metadata:
  name: tips-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tips-app
  template:
    metadata:
      labels:
        app: tips-app
    spec:
      containers:
        - name: tips-app-container
          image: robert076/tips-microservice:despicable-me-2
          ports:
            - containerPort: 1234
